### ISSUE TITLE
Fixture without trailing newline

### ISSUE THREAD

**Issue by martinring** [markdown-it/markdown-it-testgen#4]
Maybe I am missing something here but I am trying to achieve the following: I have a test case where the parsed data does not have a trailing newline:

````
example
.
:::{#refs}
:::
.
<div>
[bibliography]
</div>
.
````

I get the following error:

````
AssertionError: expected '<div id="refs">\n[bibliography]\n</div>' to equal '<div id="refs">\n[bibliography]\n</div>\n'
+ expected - actual

 <div id="refs">
 [bibliography]
-</div>
+</div>
````

Is there a way to enter such a fixture or do i have to modify the assertion framework?

**Comment by puzrin** [comment]
Current format does not allow to define fixture without trailing newline. It's not intended to replace 100% of fixtures. Just define the rest of tests manually.

**Comment by martinring** [comment]
@puzrin thank you for the information and for your great work on markdown-it
